# python3 development environment with the python3 dependencies for the application
# -----------------------------------------------------------------------------
FROM docker.corp.maana.io/alpine_python3 as dependencies
COPY requirements.txt .
RUN apk add build-base && pip3 install --no-cache-dir -r requirements.txt && apk del build-base

# -----------------------------------------------------------------------------
# Build the application
# -----------------------------------------------------------------------------
FROM dependencies as app
WORKDIR /usr/app
COPY ./*.py ./
COPY ./shared ./shared

# -----------------------------------------------------------------------------
# Test the application
# -----------------------------------------------------------------------------
FROM app as run-tests
WORKDIR /usr/app
#COPY ./tests/service/*.py ./tests/service/
#RUN coverage run --source=/usr/app -m pytest tests/service/ && coverage report

# -----------------------------------------------------------------------------
# CREATE THE DISTRIBUTION IMAGE
# -----------------------------------------------------------------------------
FROM dependencies as tested
WORKDIR /usr/app
COPY --from=app /usr/app .
ENV PORT=7357
EXPOSE 7357
CMD ["python3", "server.py"]
